# ============================================================
#  Big 12 Basketball Recruiting Radar
#  Data loaded from recruits_data.csv (generated by scrape_recruits.R)
#
#  To refresh data:
#    source('scrape_recruits.R')
# ============================================================

library(shiny)
library(ggplot2)
library(dplyr)
library(scales)
library(stringr)
library(rvest)
library(httr)
library(jsonlite)

`%||%` <- function(x, y) {
  if (is.null(x) || length(x) == 0) y else x
}

# source("scrape_recruits.R") # For data scraping functions and city geocoding

# ── on3.com team slugs ────────────────────────────────────
team_slugs <- c(
  "Arizona"        = "arizona-wildcats",
  "Arizona State"  = "arizona-state-sun-devils",
  "Baylor"         = "baylor-bears",
  "BYU"            = "byu-cougars",
  "Cincinnati"     = "cincinnati-bearcats",
  "Colorado"       = "colorado-buffaloes",
  "Houston"        = "houston-cougars",
  "Iowa State"     = "iowa-state-cyclones",
  "Kansas"         = "kansas-jayhawks",
  "Kansas State"   = "kansas-state-wildcats",
  "Oklahoma State" = "oklahoma-state-cowboys",
  "TCU"            = "tcu-horned-frogs",
  "Texas Tech"     = "texas-tech-red-raiders",
  "UCF"            = "ucf-knights",
  "Utah"           = "utah-utes",
  "West Virginia"  = "west-virginia-mountaineers"
)
big12_teams <- names(team_slugs)

# ── Campus coordinates (lat, lon) ─────────────────────────
campus_coords <- list(
  "Arizona"        = c(32.2319, -110.9501),
  "Arizona State"  = c(33.4242, -111.9281),
  "Baylor"         = c(31.5489, -97.1131),
  "BYU"            = c(40.2518, -111.6493),
  "Cincinnati"     = c(39.1329, -84.5150),
  "Colorado"       = c(40.0076, -105.2659),
  "Houston"        = c(29.7174, -95.3412),
  "Iowa State"     = c(42.0267, -93.6465),
  "Kansas"         = c(38.9543, -95.2558),
  "Kansas State"   = c(39.1836, -96.5717),
  "Oklahoma State" = c(36.1269, -97.0682),
  "TCU"            = c(32.7096, -97.3640),
  "Texas Tech"     = c(33.5843, -101.8783),
  "UCF"            = c(28.6024, -81.2001),
  "Utah"           = c(40.7649, -111.8421),
  "West Virginia"  = c(39.6350, -79.9542)
)

# ── Team brand colors ─────────────────────────────────────
team_colors <- c(
  "Arizona"        = "#AB0520", "Arizona State"  = "#8C1D40",
  "Baylor"         = "#154734", "BYU"            = "#002E5D",
  "Cincinnati"     = "#E00122", "Colorado"       = "#CFB87C",
  "Houston"        = "#C8102E", "Iowa State"     = "#F1BE48",
  "Kansas"         = "#0051A5", "Kansas State"   = "#512888",
  "Oklahoma State" = "#FF7300", "TCU"            = "#4D1979",
  "Texas Tech"     = "#CC0000", "UCF"            = "#FFC904",
  "Utah"           = "#BE0000", "West Virginia"  = "#002855"
)

# ── Team domains for logo fetch ──────────────────────────
team_domains <- c(
  "Arizona" = "arizona.edu",
  "Arizona State" = "asu.edu",
  "Baylor" = "baylor.edu",
  "BYU" = "byu.edu",
  "Cincinnati" = "uc.edu",
  "Colorado" = "colorado.edu",
  "Houston" = "uh.edu",
  "Iowa State" = "iastate.edu",
  "Kansas" = "ku.edu",
  "Kansas State" = "k-state.edu",
  "Oklahoma State" = "okstate.edu",
  "TCU" = "tcu.edu",
  "Texas Tech" = "ttu.edu",
  "UCF" = "ucf.edu",
  "Utah" = "utah.edu",
  "West Virginia" = "wvu.edu"
)

load_team_logo_map <- function(csv_file = "team_logo_urls.csv") {
  defaults <- data.frame(
    team = names(team_domains),
    logo_url = paste0("https://logo.clearbit.com/", unname(team_domains), "?size=64"),
    stringsAsFactors = FALSE
  )

  if (!file.exists(csv_file)) {
    return(setNames(defaults$logo_url, defaults$team))
  }

  x <- tryCatch(read.csv(csv_file, stringsAsFactors = FALSE), error = function(e) defaults)
  if (!all(c("team", "logo_url") %in% names(x))) {
    x <- defaults
  }

  merged <- defaults
  idx <- match(x$team, merged$team)
  valid <- !is.na(idx) & !is.na(x$logo_url) & nchar(trimws(x$logo_url)) > 0
  merged$logo_url[idx[valid]] <- x$logo_url[valid]

  setNames(merged$logo_url, merged$team)
}

# ── Haversine distance (miles) ────────────────────────────
haversine <- function(lat1, lon1, lat2, lon2) {
  R <- 3958.8
  phi1 <- lat1 * pi / 180
  phi2 <- lat2 * pi / 180
  dphi <- (lat2 - lat1) * pi / 180
  dlam <- (lon2 - lon1) * pi / 180
  a <- sin(dphi / 2)^2 + cos(phi1) * cos(phi2) * sin(dlam / 2)^2
  2 * R * asin(pmin(1, sqrt(a)))
}

# ── City → (lat,lon) lookup table ────────────────────────
# Covers every city that commonly appears in on3 recruiting data
city_db <- list(
  # Texas
  "Houston, TX" = c(29.760, -95.370), "Dallas, TX" = c(32.776, -96.797),
  "San Antonio, TX" = c(29.425, -98.494), "Austin, TX" = c(30.266, -97.750),
  "Fort Worth, TX" = c(32.725, -97.321), "El Paso, TX" = c(31.761, -106.487),
  "Lubbock, TX" = c(33.577, -101.856), "Amarillo, TX" = c(35.222, -101.831),
  "Waco, TX" = c(31.549, -97.146), "Tyler, TX" = c(32.351, -95.302),
  "Beaumont, TX" = c(30.086, -94.102), "Corpus Christi, TX" = c(27.800, -97.397),
  "Midland, TX" = c(31.997, -102.078), "Odessa, TX" = c(31.845, -102.368),
  "Plano, TX" = c(33.020, -96.699), "Arlington, TX" = c(32.736, -97.108),
  "Laredo, TX" = c(27.506, -99.507), "Pasadena, TX" = c(29.691, -95.209),
  "Mesquite, TX" = c(32.764, -96.599), "McAllen, TX" = c(26.204, -98.230),
  "Killeen, TX" = c(31.117, -97.728), "Pearland, TX" = c(29.563, -95.286),
  "Frisco, TX" = c(33.150, -96.823), "Richardson, TX" = c(32.948, -96.729),
  "Garland, TX" = c(32.913, -96.638), "Irving, TX" = c(32.814, -96.949),
  "Stephenville, TX" = c(32.220, -98.202),
  # Southeast
  "Atlanta, GA" = c(33.749, -84.388), "Charlotte, NC" = c(35.227, -80.843),
  "Raleigh, NC" = c(35.779, -78.638), "Durham, NC" = c(35.994, -78.899),
  "Greensboro, NC" = c(36.073, -79.792), "Winston-Salem, NC" = c(36.100, -80.244),
  "Memphis, TN" = c(35.149, -90.052), "Nashville, TN" = c(36.166, -86.784),
  "Knoxville, TN" = c(35.961, -83.921), "Chattanooga, TN" = c(35.045, -85.309),
  "Jacksonville, FL" = c(30.332, -81.656), "Orlando, FL" = c(28.538, -81.379),
  "Miami, FL" = c(25.761, -80.192), "Tampa, FL" = c(27.948, -82.458),
  "Tallahassee, FL" = c(30.438, -84.281), "Gainesville, FL" = c(29.651, -82.325),
  "Fort Lauderdale, FL" = c(26.122, -80.143), "West Palm Beach, FL" = c(26.715, -80.064),
  "Hialeah, FL" = c(25.858, -80.278), "St. Petersburg, FL" = c(27.773, -82.640),
  "Miami Gardens, FL" = c(25.942, -80.246), "Palm Bay, FL" = c(28.035, -80.589),
  "Birmingham, AL" = c(33.521, -86.803), "Huntsville, AL" = c(34.730, -86.586),
  "Mobile, AL" = c(30.696, -88.043), "Montgomery, AL" = c(32.361, -86.279),
  "Jackson, MS" = c(32.299, -90.184), "Gulfport, MS" = c(30.367, -89.095),
  "New Orleans, LA" = c(29.951, -90.071), "Baton Rouge, LA" = c(30.443, -91.187),
  "Shreveport, LA" = c(32.526, -93.749), "Lafayette, LA" = c(30.224, -92.020),
  "Savannah, GA" = c(32.080, -81.099), "Macon, GA" = c(32.841, -83.633),
  "Columbia, SC" = c(34.000, -81.035), "Greenville, SC" = c(34.852, -82.399),
  "Charleston, SC" = c(32.776, -79.931),
  # Midwest
  "Chicago, IL" = c(41.878, -87.630), "Rockford, IL" = c(42.271, -89.094),
  "Peoria, IL" = c(40.694, -89.589), "Joliet, IL" = c(41.526, -88.082),
  "Champaign, IL" = c(40.117, -88.244), "Springfield, IL" = c(39.801, -89.644),
  "Indianapolis, IN" = c(39.768, -86.158), "Fort Wayne, IN" = c(41.130, -85.129),
  "Evansville, IN" = c(37.975, -87.556), "Kokomo, IN" = c(40.487, -86.134),
  "Columbus, OH" = c(39.961, -82.999), "Cleveland, OH" = c(41.499, -81.695),
  "Cincinnati, OH" = c(39.103, -84.512), "Toledo, OH" = c(41.663, -83.555),
  "Akron, OH" = c(41.081, -81.519), "Canton, OH" = c(40.798, -81.379),
  "Dayton, OH" = c(39.759, -84.192),
  "Detroit, MI" = c(42.332, -83.046), "Grand Rapids, MI" = c(42.966, -85.656),
  "Flint, MI" = c(43.013, -83.688), "Lansing, MI" = c(42.733, -84.556),
  "Warren, MI" = c(42.492, -83.027), "Ann Arbor, MI" = c(42.281, -83.748),
  "Milwaukee, WI" = c(43.039, -87.907), "Madison, WI" = c(43.073, -89.401),
  "Green Bay, WI" = c(44.519, -88.020), "Oshkosh, WI" = c(44.025, -88.543),
  "Minneapolis, MN" = c(44.978, -93.265), "St. Paul, MN" = c(44.955, -93.102),
  "Rochester, MN" = c(44.023, -92.470), "Duluth, MN" = c(46.786, -92.101),
  "Kansas City, MO" = c(39.099, -94.578), "St. Louis, MO" = c(38.627, -90.199),
  "Springfield, MO" = c(37.215, -93.298), "Branson, MO" = c(36.644, -93.218),
  "Omaha, NE" = c(41.257, -96.004), "Lincoln, NE" = c(40.813, -96.703),
  "Sioux Falls, SD" = c(43.549, -96.700), "Fargo, ND" = c(46.877, -96.789),
  "Des Moines, IA" = c(41.600, -93.609), "Cedar Rapids, IA" = c(42.008, -91.645),
  "Wichita, KS" = c(37.692, -97.337), "Overland Park, KS" = c(38.982, -94.671),
  "Oklahoma City, OK" = c(35.467, -97.517), "Tulsa, OK" = c(36.154, -95.993),
  "Norman, OK" = c(35.221, -97.440), "Broken Arrow, OK" = c(36.061, -95.791),
  "Little Rock, AR" = c(34.746, -92.290), "Fayetteville, AR" = c(36.062, -94.158),
  # Northeast
  "New York, NY" = c(40.713, -74.006), "Brooklyn, NY" = c(40.650, -73.950),
  "Bronx, NY" = c(40.845, -73.865), "Queens, NY" = c(40.728, -73.795),
  "Yonkers, NY" = c(40.931, -73.899), "Syracuse, NY" = c(43.048, -76.147),
  "Buffalo, NY" = c(42.887, -78.879), "Rochester, NY" = c(43.158, -77.616),
  "Albany, NY" = c(42.651, -73.755), "Farmingdale, NY" = c(40.732, -73.443),
  "Glen Head, NY" = c(40.845, -73.628),
  "Philadelphia, PA" = c(39.952, -75.165), "Pittsburgh, PA" = c(40.440, -79.996),
  "Allentown, PA" = c(40.602, -75.470), "Lancaster, PA" = c(40.038, -76.306),
  "Harrisburg, PA" = c(40.274, -76.884),
  "Newark, NJ" = c(40.735, -74.172), "Jersey City, NJ" = c(40.729, -74.077),
  "Boston, MA" = c(42.360, -71.058), "Worcester, MA" = c(42.263, -71.802),
  "Springfield, MA" = c(42.101, -72.590), "Lynn, MA" = c(42.467, -70.944),
  "Hartford, CT" = c(41.764, -72.685), "Bridgeport, CT" = c(41.179, -73.190),
  "Waterbury, CT" = c(41.558, -73.052),
  "Providence, RI" = c(41.824, -71.413),
  "Washington, DC" = c(38.907, -77.037), "Baltimore, MD" = c(39.290, -76.612),
  "Richmond, VA" = c(37.541, -77.436), "Virginia Beach, VA" = c(36.853, -75.978),
  "Norfolk, VA" = c(36.851, -76.291), "Chesapeake, VA" = c(36.769, -76.287),
  "Hampton, VA" = c(37.031, -76.345),
  # Mountain/West
  "Denver, CO" = c(39.739, -104.984), "Colorado Springs, CO" = c(38.834, -104.822),
  "Aurora, CO" = c(39.729, -104.832), "Lakewood, CO" = c(39.705, -105.082),
  "Pueblo, CO" = c(38.255, -104.609),
  "Phoenix, AZ" = c(33.448, -112.074), "Tucson, AZ" = c(32.221, -110.969),
  "Mesa, AZ" = c(33.415, -111.831), "Chandler, AZ" = c(33.307, -111.841),
  "Tempe, AZ" = c(33.425, -111.940), "Scottsdale, AZ" = c(33.494, -111.926),
  "Las Vegas, NV" = c(36.175, -115.137), "Henderson, NV" = c(36.040, -114.982),
  "North Las Vegas, NV" = c(36.199, -115.117), "Reno, NV" = c(39.529, -119.814),
  "Salt Lake City, UT" = c(40.760, -111.891), "Provo, UT" = c(40.233, -111.658),
  "Ogden, UT" = c(41.223, -111.974), "St. George, UT" = c(37.104, -113.584),
  "Albuquerque, NM" = c(35.085, -106.651), "Santa Fe, NM" = c(35.687, -105.938),
  "Boise, ID" = c(43.615, -116.202), "Meridian, ID" = c(43.612, -116.392),
  "Spokane, WA" = c(47.659, -117.426), "Seattle, WA" = c(47.607, -122.332),
  "Tacoma, WA" = c(47.253, -122.445), "Bellevue, WA" = c(47.611, -122.192),
  "Portland, OR" = c(45.523, -122.676), "Eugene, OR" = c(44.051, -123.087),
  # California
  "Los Angeles, CA" = c(34.052, -118.244), "San Diego, CA" = c(32.715, -117.157),
  "San Jose, CA" = c(37.339, -121.894), "San Francisco, CA" = c(37.775, -122.419),
  "Fresno, CA" = c(36.737, -119.787), "Sacramento, CA" = c(38.582, -121.494),
  "Long Beach, CA" = c(33.770, -118.194), "Oakland, CA" = c(37.804, -122.271),
  "Bakersfield, CA" = c(35.373, -119.019), "Anaheim, CA" = c(33.836, -117.915),
  "Santa Ana, CA" = c(33.746, -117.868), "Riverside, CA" = c(33.954, -117.395),
  "Stockton, CA" = c(37.958, -121.291), "Modesto, CA" = c(37.640, -120.997),
  "Oxnard, CA" = c(34.197, -119.177), "Moreno Valley, CA" = c(33.937, -117.230),
  "Pomona, CA" = c(34.055, -117.752), "Torrance, CA" = c(33.836, -118.341),
  "Pasadena, CA" = c(34.148, -118.144), "Compton, CA" = c(33.896, -118.220),
  "Santa Maria, CA" = c(34.952, -120.436), "Napa, CA" = c(38.297, -122.286),
  "Castaic, CA" = c(34.489, -118.628), "Inglewood, CA" = c(33.962, -118.353),
  # Other US
  "Anchorage, AK" = c(61.218, -149.900), "Honolulu, HI" = c(21.307, -157.858),
  "Louisville, KY" = c(38.252, -85.758), "Lexington, KY" = c(38.040, -84.459),
  "Fayetteville, NC" = c(35.053, -78.879), "Asheville, NC" = c(35.579, -82.554),
  "Gary, IN" = c(41.593, -87.347), "South Bend, IN" = c(41.676, -86.252),
  "Athens, GA" = c(33.960, -83.378), "Augusta, GA" = c(33.471, -81.975),
  "Murfreesboro, TN" = c(35.846, -86.390), "Clarksville, TN" = c(36.530, -87.359),
  "Lake City, MN" = c(44.449, -92.268),
  # International / cities without state
  "Kinshasa" = c(-4.322, 15.322), "Kinshasa, Congo" = c(-4.322, 15.322),
  "Yaoundé" = c(3.867, 11.517), "Cameroon" = c(3.848, 11.502),
  "Rome, Rome" = c(41.902, 12.496), "Rome, Italy" = c(41.902, 12.496),
  "Montreal, QC" = c(45.501, -73.568), "Edmonton, AB" = c(53.546, -113.490),
  "Vancouver, BC" = c(49.246, -123.117), "Toronto, ON" = c(43.653, -79.383),
  "Germany" = c(51.166, 10.452), "Berlin, Germany" = c(52.520, 13.405),
  "France" = c(46.227, 2.213), "Paris, France" = c(48.857, 2.352),
  "Nigeria" = c(9.082, 8.675), "Lagos, Nigeria" = c(6.455, 3.384),
  "Senegal" = c(14.497, -14.452), "Australia" = c(-25.274, 133.775),
  "Spain" = c(40.463, -3.749), "Serbia" = c(44.017, 21.006),
  "Croatia" = c(45.100, 15.202), "Bahamas" = c(25.025, -77.980),
  "Jamaica" = c(18.110, -77.297),
  "Hickory, NC" = c(35.729, -81.338)
)

# ── Geocode a hometown string ─────────────────────────────
geocode_city <- function(hometown) {
  if (is.na(hometown) || nchar(trimws(hometown)) == 0) {
    return(NULL)
  }
  key <- trimws(hometown)
  # Direct
  if (!is.null(city_db[[key]])) {
    return(city_db[[key]])
  }
  # Remove parentheses
  key2 <- str_replace_all(key, "[()]", "") %>% trimws()
  if (!is.null(city_db[[key2]])) {
    return(city_db[[key2]])
  }
  # Try just first two comma parts
  parts <- str_split(key2, ",")[[1]]
  if (length(parts) >= 2) {
    k3 <- paste0(trimws(parts[1]), ", ", trimws(parts[2]))
    if (!is.null(city_db[[k3]])) {
      return(city_db[[k3]])
    }
  }
  NULL
}

# ── Scrape one page from on3.com ──────────────────────────
scrape_on3_page <- function(team, year, slug, verbose = TRUE) {
  url <- sprintf(
    "https://www.on3.com/college/%s/basketball/%d/commits/",
    slug, year
  )
  if (verbose) message(sprintf("  Fetching %s %d ...", team, year))

  tryCatch(
    {
      resp <- GET(
        url,
        user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"),
        add_headers(
          "Accept-Language" = "en-US,en;q=0.9",
          "Accept" = "text/html,application/xhtml+xml"
        ),
        timeout(20)
      )
      if (status_code(resp) != 200) {
        return(NULL)
      }

      html_text <- content(resp, as = "text", encoding = "UTF-8")

      # Extract Hometown values — on3 uses "Hometown:\n(City, ST)" pattern
      # Multiple extraction strategies
      hometowns <- character(0)

      # Strategy 1: regex on raw HTML for hometown patterns
      m1 <- str_match_all(
        html_text,
        "Hometown[^(]*\\(([^)]{2,40})\\)"
      )[[1]]
      if (nrow(m1) > 0) hometowns <- c(hometowns, m1[, 2])

      # Strategy 2: parse with rvest
      if (length(hometowns) == 0) {
        page <- read_html(html_text)
        # Look for dt/dd pairs
        dts <- page %>%
          html_nodes("dt") %>%
          html_text(trim = TRUE)
        dds <- page %>%
          html_nodes("dd") %>%
          html_text(trim = TRUE)
        ht_idx <- which(str_detect(dts, "(?i)hometown"))
        if (length(ht_idx) > 0 && max(ht_idx) <= length(dds)) {
          hometowns <- dds[ht_idx]
          hometowns <- str_replace_all(hometowns, "[()]", "") %>% trimws()
        }
      }

      # Strategy 3: look for city-state pattern after "Hometown"
      if (length(hometowns) == 0) {
        m3 <- str_match_all(
          html_text,
          '"hometown"[^"]*"([A-Za-z ]+(?:,\\s*[A-Z]{2})?)"'
        )[[1]]
        if (nrow(m3) > 0) hometowns <- m3[, 2]
      }

      hometowns <- hometowns[nchar(trimws(hometowns)) > 1]
      hometowns <- trimws(hometowns)

      if (length(hometowns) == 0) {
        return(NULL)
      }

      data.frame(
        team = team, year = year, hometown = hometowns,
        stringsAsFactors = FALSE
      )
    },
    error = function(e) {
      message(sprintf("    Error: %s", e$message))
      NULL
    }
  )
}

# ── Compute distances ─────────────────────────────────────
add_distances <- function(df) {
  campus <- campus_coords
  df %>%
    rowwise() %>%
    mutate(
      coords = list(geocode_city(hometown)),
      ht_lat = if (!is.null(coords)) coords[1] else NA_real_,
      ht_lon = if (!is.null(coords)) coords[2] else NA_real_,
      camp_lat = campus[[team]][1],
      camp_lon = campus[[team]][2],
      distance_miles = if (!is.na(ht_lat)) {
        haversine(ht_lat, ht_lon, camp_lat, camp_lon)
      } else {
        NA_real_
      }
    ) %>%
    ungroup() %>%
    filter(!is.na(distance_miles)) %>%
    select(team, year, hometown, distance_miles)
}

# ── Load data from CSV ────────────────────────────────────
load_recruiting_data <- function(csv_file = "recruits_data.csv") {
  if (!file.exists(csv_file)) {
    warning(sprintf("Data file '%s' not found.\n  Run scrape_recruits.R to create it.", csv_file))
    return(data.frame(
      team = character(), year = integer(),
      hometown = character(), distance_miles = numeric()
    ))
  }
  message(sprintf("Loading data from %s...", csv_file))
  df <- read.csv(csv_file, stringsAsFactors = FALSE)

  # Backward compatibility for older CSVs that didn't include player-level columns.
  if (!"player_name" %in% names(df)) df$player_name <- NA_character_
  if (!"player_slug" %in% names(df)) df$player_slug <- NA_character_
  if (!"high_school" %in% names(df)) df$high_school <- NA_character_
  if (!"status" %in% names(df)) df$status <- NA_character_

  message(sprintf("Loaded %d recruits", nrow(df)))
  df
}

# ─────────────────────────────────────────────────────────
#  UI
# ─────────────────────────────────────────────────────────
ui <- fluidPage(
  tags$head(
    tags$link(
      rel = "stylesheet",
      href = "https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@500;700&family=Manrope:wght@300;400;500;600;700&display=swap"
    ),
    tags$script(HTML("$(document).on('click keydown', '.help-dot', function(e) {
      if (e.type === 'keydown' && e.key !== 'Enter' && e.key !== ' ') return;
      e.preventDefault();
      var $dot = $(this);
      $('.help-dot.is-open').not($dot).removeClass('is-open');
      $dot.toggleClass('is-open');
    });
    $(document).on('click', function(e) {
      if (!$(e.target).closest('.help-dot').length) {
        $('.help-dot.is-open').removeClass('is-open');
      }
    });")),
    tags$style(HTML("
      * { box-sizing:border-box; }
      body {
        background:linear-gradient(170deg,#f3eee4 0%,#eef4fa 54%,#f7f1e6 100%);
        color:#232733;
        font-family:'Manrope',sans-serif;
        font-size:16px;
        margin:0;
        padding:0;
      }

      .app-header {
        background:linear-gradient(130deg,#f7ecd5 0%,#fbfcfe 48%,#e1edf9 100%);
        border-bottom:1px solid #d8deea;
        box-shadow:0 12px 28px rgba(29,43,71,.08);
        padding:20px 28px 16px;
        display:flex;
        align-items:flex-end;
        gap:14px;
      }
      .app-title {
        font-family:'Barlow Condensed',sans-serif;
        font-size:2.3rem;
        letter-spacing:1px;
        color:#213459;
        line-height:1;
        margin:0;
      }
      .app-sub {
        font-size:0.88rem;
        color:#5f6f89;
        letter-spacing:1px;
        text-transform:uppercase;
        margin-bottom:3px;
      }
      .badge-conf {
        background:#ffb703;
        color:#1b2d4f;
        font-family:'Barlow Condensed',sans-serif;
        font-size:0.95rem;
        letter-spacing:1px;
        padding:2px 10px;
        border-radius:999px;
        display:inline-block;
        margin-bottom:4px;
      }
      .badge-live {
        background:#e8fff0;
        border:1px solid #9bd2ae;
        color:#277147;
        font-size:0.70rem;
        letter-spacing:.6px;
        padding:2px 9px;
        border-radius:999px;
        display:inline-block;
        margin-bottom:4px;
        margin-left:6px;
      }

      .stats-strip {
        display:flex;
        gap:14px;
        padding:16px 24px;
        border-bottom:1px solid #d8deea;
        background:linear-gradient(125deg,#2a4667 0%,#35577d 54%,#43698f 100%);
        flex-wrap:wrap;
      }
      .stat-card {
        background:linear-gradient(165deg,#fffdfb 0%,#f2f7fd 100%);
        border:1px solid #9db2d1;
        border-radius:12px;
        padding:12px 14px;
        flex:1;
        min-width:118px;
        text-align:center;
        box-shadow:0 8px 18px rgba(8,18,38,.23);
      }
      .stat-val {
        font-family:'Barlow Condensed',sans-serif;
        font-size:1.78rem;
        color:#1a3868;
        line-height:1;
      }
      .stat-lbl {
        font-size:0.78rem;
        color:#4c5f80;
        letter-spacing:1.2px;
        text-transform:uppercase;
        margin-top:6px;
      }

      .help-dot {
        display:inline-flex;
        width:16px;
        height:16px;
        border-radius:50%;
        align-items:center;
        justify-content:center;
        background:#e4eefc;
        color:#1f4276;
        border:1px solid #bcd0ee;
        font-size:10px;
        font-weight:800;
        margin-left:4px;
        cursor:help;
        position:relative;
        vertical-align:middle;
        outline:none;
      }
      .help-dot::after {
        content:attr(data-help);
        position:absolute;
        left:50%;
        bottom:calc(100% + 10px);
        transform:translateX(-50%);
        min-width:180px;
        max-width:260px;
        padding:10px 12px;
        border-radius:10px;
        background:#173057;
        color:#ffffff;
        font-size:0.84rem;
        font-weight:500;
        line-height:1.45;
        letter-spacing:0;
        text-transform:none;
        box-shadow:0 12px 24px rgba(9,20,38,.28);
        opacity:0;
        pointer-events:none;
        transition:opacity .16s ease;
        z-index:20;
        text-align:left;
      }
      .help-dot::before {
        content:'';
        position:absolute;
        left:50%;
        bottom:calc(100% + 4px);
        transform:translateX(-50%);
        border-left:6px solid transparent;
        border-right:6px solid transparent;
        border-top:6px solid #173057;
        opacity:0;
        pointer-events:none;
        transition:opacity .16s ease;
        z-index:21;
      }
      .help-dot:hover::after,
      .help-dot:hover::before,
      .help-dot:focus::after,
      .help-dot:focus::before,
      .help-dot.is-open::after,
      .help-dot.is-open::before {
        opacity:1;
      }

      .main-wrap { display:flex; min-height:calc(100vh - 96px); }

      .sidebar {
        width:292px;
        min-width:292px;
        background:linear-gradient(180deg,#f6f9fd 0%,#eef4fa 100%);
        border-right:1px solid #d8deea;
        padding:20px 18px;
        display:flex; flex-direction:column; gap:18px; }
      .sec-lbl { font-size:0.78rem; letter-spacing:1.8px;
        text-transform:uppercase; color:#1a447f; margin-bottom:6px;
        font-weight:600; }
      hr.sdiv { border:none; border-top:1px solid #dce4f2; margin:4px 0; }
      .shiny-input-container { margin-bottom:0 !important; }
      label { color:#4f607e !important; font-size:0.92rem !important;
              font-weight:500 !important; margin-bottom:5px !important; }
      .selectize-control .selectize-input {
        background:#ffffff !important; border:2px solid #b6c9e2 !important;
        color:#213459 !important; border-radius:7px !important;
        box-shadow:0 2px 0 rgba(50,82,122,.08) !important; font-size:0.94rem !important; }
      .selectize-control .selectize-input.focus {
        border-color:#356fbf !important;
        box-shadow:0 0 0 3px rgba(53,111,191,.18) !important; }
      .selectize-dropdown { background:#ffffff !important;
        border:1px solid #cdd7e8 !important; color:#213459 !important;
        font-size:0.92rem !important; }
      .selectize-dropdown-content .option:hover,
      .selectize-dropdown-content .option.active {
        background:#eff5ff !important; color:#1a447f !important; }
      input[type=checkbox],input[type=radio] { accent-color:#2a6fdb; }
      .checkbox label,.radio label { color:#334b70 !important;
        font-size:0.92rem !important; }
      .irs--shiny .irs-bar { background:#2a6fdb !important; }
      .irs--shiny .irs-handle { background:#2a6fdb !important;
        border-color:#2a6fdb !important; }
      .irs--shiny .irs-from,.irs--shiny .irs-to,.irs--shiny .irs-single {
        background:#2a6fdb !important; color:#ffffff !important;
        font-weight:600 !important; }
      .irs--shiny .irs-line { background:#d3dff1 !important; }
      .irs--shiny .irs-grid-text { color:#5f6f89 !important;
        font-size:0.80rem !important; }
      .sidebar-note {
        font-size:0.86rem;
        color:#4f607e;
        line-height:1.65;
      }

      .plot-area { flex:1; padding:20px 24px; overflow:auto; background:linear-gradient(180deg,rgba(255,255,255,.22) 0%, rgba(233,241,249,.12) 100%); }
      .plot-hdr { display:flex; justify-content:space-between;
        align-items:baseline; margin-bottom:12px; }
      .plot-ttl { font-family:'Barlow Condensed',sans-serif; font-size:1.45rem;
        letter-spacing:1px; color:#213459; }
      .plot-cap { font-size:0.84rem; color:#5f6f89; }

      .hero-card {
        background:linear-gradient(180deg,#fffdfa 0%,#f5f8fc 100%);
        border:1px solid #ccd9ea;
        border-radius:16px;
        padding:16px 18px 14px;
        box-shadow:0 16px 28px rgba(18,36,66,.11);
        margin-bottom:14px;
      }
      .hero-head {
        display:flex;
        justify-content:space-between;
        align-items:flex-start;
        flex-wrap:wrap;
        gap:12px;
        margin-bottom:12px;
      }
      .hero-title {
        font-family:'Barlow Condensed',sans-serif;
        font-size:1.5rem;
        letter-spacing:1px;
        color:#173a72;
        line-height:1;
      }
      .hero-sub {
        font-size:.84rem;
        color:#5b6e8e;
        margin-top:7px;
      }
      .hero-badges {
        display:grid;
        grid-template-columns:repeat(auto-fit, minmax(180px, 1fr));
        gap:10px;
        margin:8px 0 14px;
      }
      .story-badge {
        background:linear-gradient(155deg,#f8fbff 0%,#eef5ff 100%);
        border:1px solid #d6e2f4;
        border-radius:12px;
        padding:10px 12px;
        box-shadow:0 8px 14px rgba(22,40,72,.07);
      }
      .story-kicker {
        font-size:.70rem;
        text-transform:uppercase;
        letter-spacing:1.35px;
        color:#6a7f9f;
      }
      .story-team {
        margin-top:4px;
        font-family:'Barlow Condensed',sans-serif;
        font-size:1.28rem;
        color:#15396d;
        letter-spacing:.5px;
        line-height:1;
      }
      .story-value {
        margin-top:4px;
        font-size:.88rem;
        color:#39547f;
      }
      .hero-note {
        background:#eef4fb;
        border:1px solid #d1deef;
        border-radius:10px;
        padding:10px 12px;
        margin-top:12px;
        color:#284a7d;
        font-size:.88rem;
      }

      .hero-tabs .nav {
        display:flex;
        gap:8px;
        flex-wrap:wrap;
        border-bottom:none;
        margin-bottom:12px;
      }
      .hero-tabs .nav > li {
        float:none;
      }
      .hero-tabs .nav > li > a {
        margin-right:0;
        border:2px solid #c3d4e8;
        border-radius:999px;
        padding:9px 16px;
        background:#e5edf7;
        color:#28476f;
        font-size:0.86rem;
        font-weight:700;
        letter-spacing:0.2px;
      }
      .hero-tabs .nav > li > a:hover,
      .hero-tabs .nav > li > a:focus {
        background:#dbe7f4;
        color:#1f416c;
      }
      .hero-tabs .nav > li.active > a,
      .hero-tabs .nav > li.active > a:hover,
      .hero-tabs .nav > li.active > a:focus {
        background:linear-gradient(135deg,#2a496d 0%,#40658f 100%);
        color:#ffffff;
        border:2px solid #2b4f77;
      }
      .hero-tabs .tab-content > .tab-pane {
        padding:6px 0 0;
        border:none;
        background:transparent;
        box-shadow:none;
      }

      .supp-card {
        background:#ffffff;
        border:1px solid #d8deea;
        border-radius:13px;
        padding:0;
        box-shadow:0 8px 16px rgba(20,40,73,.08);
      }
      .loading-box { color:#294f90; font-family:'Barlow Condensed',sans-serif;
        font-size:1.1rem; letter-spacing:2px; padding:60px 20px;
        text-align:center; }
      .loading-sub { font-family:'Manrope',sans-serif; font-size:0.8rem;
        color:#5f6f89; margin-top:10px; line-height:1.6; }

      .tab-pane {
        background:#ffffff;
        border:1px solid #d8deea;
        border-top:none;
        border-radius:0 0 12px 12px;
        padding:18px;
        box-shadow:none;
      }
      .nav-tabs > li > a {
        color:#35527f;
        font-size:0.90rem;
        font-weight:600;
      }
      .nav-tabs > li.active > a,
      .nav-tabs > li.active > a:hover,
      .nav-tabs > li.active > a:focus {
        color:#1a3868;
        background:#ffffff;
        border:1px solid #d8deea;
        border-bottom-color:#ffffff;
      }

      .team-logo-strip {
        display:flex;
        flex-wrap:wrap;
        gap:8px;
        margin:8px 0 12px;
      }
      .logo-chip {
        display:inline-flex;
        align-items:center;
        gap:8px;
        padding:7px 12px;
        border-radius:999px;
        color:#ffffff;
        font-size:.84rem;
        font-weight:700;
        box-shadow:0 6px 10px rgba(15,28,52,.20);
      }
      .logo-mark {
        width:22px;
        height:22px;
        border-radius:50%;
        background:rgba(255,255,255,.20);
        display:inline-flex;
        align-items:center;
        justify-content:center;
        font-size:.60rem;
        font-weight:800;
      }
      .logo-img {
        width:22px;
        height:22px;
        border-radius:50%;
        background:#ffffff;
        border:1px solid rgba(255,255,255,.55);
        object-fit:contain;
      }

      .help-panel {
        line-height:1.75;
        color:#334b70;
        font-size:1rem;
      }
      .help-panel h4 {
        margin:8px 0 6px;
        font-family:'Barlow Condensed',sans-serif;
        letter-spacing:.7px;
        color:#1d3d70;
      }

      .action-button,
      .btn-default,
      .btn.btn-default {
        background:linear-gradient(140deg,#2f5f90 0%,#3e78b6 100%) !important;
        border:2px solid #2b5f95 !important;
        color:#ffffff !important;
        font-weight:700 !important;
        font-size:0.90rem !important;
        letter-spacing:0.3px;
        border-radius:10px !important;
        padding:8px 12px !important;
        box-shadow:0 6px 12px rgba(25,54,88,.22);
      }
      .action-button:hover,
      .btn-default:hover,
      .btn.btn-default:hover,
      .action-button:focus,
      .btn-default:focus,
      .btn.btn-default:focus {
        background:linear-gradient(140deg,#2b567f 0%,#36699f 100%) !important;
        border-color:#244e79 !important;
        color:#ffffff !important;
      }

      @media (max-width: 1080px) {
        .sidebar { width:100%; min-width:100%; border-right:none; border-bottom:1px solid #d8deea; }
        .main-wrap { flex-direction:column; }
        .plot-area { padding:18px 16px; }
        .stats-strip { padding:14px 16px; }
      }
    "))
  ),

  # ── Header ──────────────────────────────────────────────
  div(
    class = "app-header",
    div(
      div(class = "badge-conf", "BIG 12 MEN'S BASKETBALL"),
      span(class = "badge-live", "LIVE DATA · CSV BACKED"),
      div(class = "app-title", "BASKETBALL RECRUITING RADAR")
    ),
    div(
      style = "margin-left:auto; text-align:right;",
      div(class = "app-sub", "Visual Big 12 basketball recruiting distance patterns by team and class")
    )
  ),

  # ── Stats strip ─────────────────────────────────────────
  div(
    class = "stats-strip",
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_n", inline = TRUE)),
      div(class = "stat-lbl", HTML("Recruits <span class='help-dot' data-help='Total recruits included after filters are applied.' tabindex='0' role='button' aria-label='Explain recruits metric'>?</span>"))
    ),
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_med", inline = TRUE)),
      div(class = "stat-lbl", HTML("Median Miles <span class='help-dot' data-help='Middle value of recruiting distance. Half of recruits are closer and half are farther.' tabindex='0' role='button' aria-label='Explain median miles metric'>?</span>"))
    ),
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_avg", inline = TRUE)),
      div(class = "stat-lbl", HTML("Avg Miles <span class='help-dot' data-help='Mean distance across all visible recruits.' tabindex='0' role='button' aria-label='Explain average miles metric'>?</span>"))
    ),
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_loc", inline = TRUE)),
      div(class = "stat-lbl", HTML("Local Share <span class='help-dot' data-help='Percent of recruits within 300 miles of campus.' tabindex='0' role='button' aria-label='Explain local share metric'>?</span>"))
    ),
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_natl", inline = TRUE)),
      div(class = "stat-lbl", HTML("National Share <span class='help-dot' data-help='Percent of recruits more than 1,000 miles from campus.' tabindex='0' role='button' aria-label='Explain national share metric'>?</span>"))
    ),
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_intl", inline = TRUE)),
      div(class = "stat-lbl", HTML("Long-Haul Share <span class='help-dot' data-help='Percent of recruits more than 2,500 miles from campus.' tabindex='0' role='button' aria-label='Explain long-haul share metric'>?</span>"))
    )
  ),

  # ── Body ────────────────────────────────────────────────
  div(
    class = "main-wrap",

    # Sidebar
    div(
      class = "sidebar",
      div(
        div(class = "sec-lbl", HTML("Year Range <span class='help-dot' data-help='Choose recruiting classes to include in all visuals.' tabindex='0' role='button' aria-label='Explain year range filter'>?</span>")),
        sliderInput("yr", NULL,
          min = 2021, max = 2025,
          value = c(2021, 2025), step = 1, sep = "", ticks = TRUE
        )
      ),
      hr(class = "sdiv"),
      div(
        div(class = "sec-lbl", HTML("Teams <span class='help-dot' data-help='Start with one team, then add peers to compare spread and recruiting reach.' tabindex='0' role='button' aria-label='Explain teams filter'>?</span>")),
        selectizeInput("teams", NULL,
          choices = big12_teams,
          selected = "Arizona", multiple = TRUE,
          options = list(
            placeholder = "Select Big 12 basketball teams…",
            plugins = list("remove_button")
          )
        )
      ),
      hr(class = "sdiv"),
      conditionalPanel(
        condition = "input.view_tab === 'histogram'",
        div(
          div(class = "sec-lbl", HTML("Histogram Mode <span class='help-dot' data-help='Supplemental view: compare all teams in one panel or split by team facets.' tabindex='0' role='button' aria-label='Explain histogram mode'>?</span>")),
          radioButtons("hist_mode", NULL,
            choices = c(
              "All Teams Overlaid" = "overlay",
              "Facet by Team" = "facet"
            ),
            selected = "overlay"
          )
        )
      ),
      conditionalPanel(
        condition = "input.view_tab === 'histogram'",
        hr(class = "sdiv"),
        div(
          div(class = "sec-lbl", HTML("Bin Width (miles) <span class='help-dot' data-help='Larger bins smooth the histogram; smaller bins show more detail.' tabindex='0' role='button' aria-label='Explain histogram bin width'>?</span>")),
          sliderInput("bw", NULL, min = 50, max = 400, value = 150, step = 25)
        )
      ),
      hr(class = "sdiv"),
      div(
        div(class = "sec-lbl", HTML("Options <span class='help-dot' data-help='Turn plot layers on or off and optionally remove very long-distance outliers.' tabindex='0' role='button' aria-label='Explain display options'>?</span>")),
        checkboxInput("dens", "Overlay density curve", TRUE),
        checkboxInput("show_refs", "Show distance markers", TRUE),
        checkboxInput("show_points", "Show individual points on box plot", TRUE),
        checkboxInput("drop_intl", "Exclude international recruits (>4000 mi)", FALSE),
        actionButton("rescrape", "Reload Basketball Data", width = "100%")
      ),
      hr(class = "sdiv"),
      div(
        div(class = "sec-lbl", "Color Key"),
        div(
          class = "sidebar-note",
          HTML("<b style='color:#b88200;'>Current class</b> vs <b style='color:#5279b5;'>Prior classes</b><br>
                The main box plot is the primary comparison view")
        )
      ),
      div(
        class = "sidebar-note",
        "Tip: Start with Arizona, then add teams to compare spread and recruiting reach."
      )
    ),

    # Plot area
    div(
      class = "plot-area",
      div(
        class = "plot-hdr",
        div(class = "plot-ttl", "Big 12 Basketball Recruiting Distance Dashboard"),
        div(class = "plot-cap", textOutput("caption", inline = TRUE))
      ),
      uiOutput("team_logos"),
      div(
        class = "hero-card",
        div(
          class = "hero-head",
          div(
            div(class = "hero-title", HTML("Primary View: Basketball Team Distance Distribution <span class='help-dot' data-help='Each box summarizes basketball recruiting distance distribution for a team. Line in box = median, box = middle 50 percent, whiskers and outliers = spread and extremes.' tabindex='0' role='button' aria-label='Explain primary box plot'>?</span>")),
            div(class = "hero-sub", "Box plot stays primary, but the histogram, QA table, and guide are now one click away inside this same view.")
          )
        ),
        div(
          class = "hero-tabs",
          tabsetPanel(
            id = "view_tab",
            selected = "box",
            type = "tabs",
            tabPanel(
              "Box Plot",
              value = "box",
              uiOutput("hero_badges"),
              plotOutput("box_plot", height = "640px", width = "100%"),
              div(class = "hero-note", textOutput("hero_note", inline = TRUE))
            ),
            tabPanel("Histogram", value = "histogram", plotOutput("hist_plot", height = "500px", width = "100%")),
            tabPanel("QA / QC", value = "qa", dataTableOutput("qa_table")),
            tabPanel(
              "How To Read This",
              value = "guide",
              div(
                class = "help-panel",
                h4("What the box plot shows"),
                tags$ul(
                  tags$li("Each team appears on the y-axis; farther right means longer recruiting distance."),
                  tags$li("Gold represents the current class in the selected range; blue represents prior classes."),
                  tags$li("Median points and labels show the typical distance for each team in the current class.")
                ),
                h4("Recommended workflow"),
                tags$ol(
                  tags$li("Select 2-6 teams to keep comparisons readable."),
                  tags$li("Set year range, then review medians and spread in the main box plot."),
                  tags$li("Open Histogram for shape details and QA / QC Table for player-level verification.")
                ),
                h4("Data notes"),
                tags$p("Distances are straight-line (haversine) from recruit hometown to campus and are loaded from local CSV data artifacts.")
              )
            )
          )
        )
      )
    )
  )
)

# ─────────────────────────────────────────────────────────
#  SERVER
# ─────────────────────────────────────────────────────────
server <- function(input, output, session) {
  rv_data <- reactiveVal(NULL)
  rv_loading <- reactiveVal(TRUE)
  team_logo_map <- load_team_logo_map("team_logo_urls.csv")

  # Initial load
  observe({
    rv_loading(TRUE)
    withProgress(
      message = "Loading recruit data…",
      detail = "Reading from recruits_data.csv",
      value = 0,
      {
        df <- tryCatch(load_recruiting_data("recruits_data.csv"),
          error = function(e) {
            showNotification(paste("Load error:", e$message), type = "error")
            data.frame(
              team = character(), year = integer(),
              hometown = character(), distance_miles = numeric()
            )
          }
        )
        rv_data(df)
      }
    )
    rv_loading(FALSE)
  })

  # Reload data button
  observeEvent(input$rescrape, {
    rv_loading(TRUE)
    withProgress(message = "Reloading recruits_data.csv…", value = 0, {
      df <- tryCatch(load_recruiting_data("recruits_data.csv"),
        error = function(e) rv_data()
      )
      rv_data(df)
    })
    rv_loading(FALSE)
    showNotification("Data reloaded!", type = "message")
  })

  # ── Filtered reactive ──────────────────────────────────
  fdf <- reactive({
    req(rv_data(), nrow(rv_data()) > 0)
    df <- rv_data() %>%
      filter(
        team %in% input$teams,
        year >= input$yr[1],
        year <= input$yr[2]
      )
    if (input$drop_intl) df <- filter(df, distance_miles <= 4000)
    df
  })

  # ── Stats ──────────────────────────────────────────────
  output$s_n <- renderText({
    req(fdf())
    comma(nrow(fdf()))
  })
  output$s_med <- renderText({
    req(fdf())
    comma(round(median(fdf()$distance_miles)))
  })
  output$s_avg <- renderText({
    req(fdf())
    comma(round(mean(fdf()$distance_miles)))
  })
  output$s_loc <- renderText({
    req(fdf())
    paste0(round(mean(fdf()$distance_miles <= 300) * 100), "%")
  })
  output$s_natl <- renderText({
    req(fdf())
    paste0(round(mean(fdf()$distance_miles > 1000) * 100), "%")
  })
  output$s_intl <- renderText({
    req(fdf())
    paste0(round(mean(fdf()$distance_miles > 2500) * 100), "%")
  })
  output$caption <- renderText({
    req(fdf())
    paste0(
      length(input$teams), " teams · ",
      input$yr[1], "–", input$yr[2], " · ",
      nrow(fdf()), " recruits"
    )
  })
  output$hero_note <- renderText({
    req(fdf())
    df <- fdf()
    current_year <- max(df$year, na.rm = TRUE)
    current_df <- df %>% filter(year == current_year)
    if (nrow(current_df) == 0) {
      return("Tip: include the latest class year to unlock the current-vs-prior comparison layer.")
    }
    med_current <- round(median(current_df$distance_miles, na.rm = TRUE))
    iqr_current <- round(IQR(current_df$distance_miles, na.rm = TRUE))
    paste0(
      "Current class ", current_year, " median distance is ", comma(med_current),
      " miles with an IQR of ", comma(iqr_current),
      " miles. Use the median labels on each row to compare teams quickly."
    )
  })
  output$hero_badges <- renderUI({
    req(fdf())
    df <- fdf()
    current_year <- max(df$year, na.rm = TRUE)
    current_df <- df %>%
      filter(year == current_year) %>%
      group_by(team) %>%
      summarize(
        recruits = n(),
        median_miles = median(distance_miles, na.rm = TRUE),
        local_share = mean(distance_miles <= 300, na.rm = TRUE),
        .groups = "drop"
      )

    req(nrow(current_df) > 0)

    most_local <- current_df %>%
      arrange(desc(local_share), median_miles, desc(recruits)) %>%
      slice(1)
    widest_reach <- current_df %>%
      arrange(desc(median_miles), desc(recruits)) %>%
      slice(1)
    largest_class <- current_df %>%
      arrange(desc(recruits), median_miles) %>%
      slice(1)

    badge <- function(kicker, team_name, value_text) {
      div(
        class = "story-badge",
        div(class = "story-kicker", kicker),
        div(class = "story-team", team_name),
        div(class = "story-value", value_text)
      )
    }

    div(
      class = "hero-badges",
      badge(
        "Best Local Footprint",
        most_local$team,
        paste0(round(most_local$local_share * 100), "% within 300 miles in ", current_year)
      ),
      badge(
        "Widest Current Reach",
        widest_reach$team,
        paste0(comma(round(widest_reach$median_miles)), " mile median in ", current_year)
      ),
      badge(
        "Largest Current Class",
        largest_class$team,
        paste0(largest_class$recruits, " recruits in ", current_year)
      )
    )
  })

  output$team_logos <- renderUI({
    req(input$teams)
    selected <- input$teams
    if (length(selected) == 0) {
      return(NULL)
    }
    chips <- lapply(selected, function(tm) {
      mark <- toupper(paste0(substr(tm, 1, 1), substr(gsub("[^A-Za-z]", "", tm), 2, 2)))
      logo_url <- team_logo_map[[tm]] %||% ""

      div(
        class = "logo-chip",
        style = paste0("background:", team_colors[[tm]], ";"),
        if (nchar(logo_url) > 0) {
          tags$img(
            class = "logo-img",
            src = logo_url,
            alt = paste0(tm, " logo")
          )
        },
        span(class = "logo-mark", mark),
        span(tm)
      )
    })
    div(class = "team-logo-strip", chips)
  })

  output$qa_table <- renderDataTable(
    {
      df <- fdf()
      req(nrow(df) > 0)

      df %>%
        transmute(
          team = team,
          year = year,
          player = ifelse(is.na(player_name) | player_name == "", "(missing)", player_name),
          hometown = hometown,
          high_school = ifelse(is.na(high_school) | high_school == "", "(missing)", high_school),
          status = ifelse(is.na(status) | status == "", "(missing)", status),
          distance_miles = round(distance_miles, 1)
        ) %>%
        arrange(desc(year), team, player)
    },
    options = list(
      pageLength = 12,
      order = list(list(1, "desc"), list(0, "asc"), list(2, "asc")),
      scrollX = TRUE
    )
  )

  output$box_plot <- renderPlot(
    {
      df <- fdf()
      req(nrow(df) > 0)
      max_yr <- max(df$year, na.rm = TRUE)
      df <- df %>%
        mutate(
          era = ifelse(year == max_yr, "current", "prior"),
          team = factor(team, levels = names(sort(tapply(distance_miles, team, median, na.rm = TRUE))))
        )

      current_med <- df %>%
        filter(era == "current") %>%
        group_by(team) %>%
        summarize(median_mi = median(distance_miles, na.rm = TRUE), .groups = "drop")

      ref_labels <- data.frame(
        x = c(300, 1000, 2000),
        y = length(levels(df$team)) + 0.45,
        label = c("Local", "National", "Long-haul")
      )

      p <- ggplot(df, aes(x = distance_miles, y = team, fill = era)) +
        geom_boxplot(
          position = position_dodge2(width = 0.76, preserve = "single"),
          width = 0.66,
          outlier.alpha = 0.22,
          outlier.size = 1.6,
          color = "#2a3b5f",
          linewidth = 0.55
        ) +
        geom_point(
          data = current_med,
          aes(x = median_mi, y = team),
          inherit.aes = FALSE,
          shape = 21,
          size = 3.2,
          fill = "#ffd166",
          color = "#735200",
          stroke = 0.75
        ) +
        geom_text(
          data = current_med,
          aes(x = median_mi, y = team, label = paste0(comma(round(median_mi)), " mi")),
          inherit.aes = FALSE,
          nudge_x = 70,
          size = 3,
          color = "#6c4d00",
          fontface = "bold",
          family = "Manrope"
        ) +
        scale_fill_manual(
          values = c(current = "#b88200", prior = "#5279b5"),
          labels = c(
            current = paste0("Current class (", max_yr, ")"),
            prior = paste0("Prior classes (", input$yr[1], "-", max_yr - 1, ")")
          ),
          name = "Class Group"
        ) +
        scale_x_continuous(
          labels = label_comma(suffix = " mi"),
          breaks = c(0, 300, 600, 1000, 1500, 2000, 2500, 3000),
          expand = expansion(mult = c(0.01, 0.18))
        ) +
        labs(x = "Distance from hometown to campus", y = NULL) +
        theme_minimal(base_family = "Manrope") +
        theme(
          panel.background = element_rect(fill = "#ffffff", color = NA),
          plot.background = element_rect(fill = "#ffffff", color = NA),
          panel.grid.minor = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.major.x = element_line(color = "#e6edf8"),
          axis.text = element_text(color = "#344a6f", size = 10),
          axis.title = element_text(color = "#22395f", face = "bold"),
          legend.position = "top",
          legend.title = element_text(color = "#22395f", face = "bold"),
          legend.background = element_rect(fill = "#f7faff", color = "#d3e0f4"),
          legend.key = element_rect(fill = "#f7faff", color = NA),
          plot.margin = margin(12, 30, 10, 8)
        )

      if (isTRUE(input$show_refs)) {
        p <- p + geom_vline(
          xintercept = c(300, 1000, 2000),
          linetype = c("dashed", "dashed", "dotdash"),
          color = c("#a8b8d4", "#93a7cb", "#7c95c4"),
          linewidth = c(0.5, 0.6, 0.8)
        ) +
          geom_label(
            data = ref_labels,
            aes(x = x, y = y, label = label),
            inherit.aes = FALSE,
            size = 2.8,
            label.size = 0,
            fill = "#eef4ff",
            color = "#4f6790",
            fontface = "bold",
            family = "Manrope",
            alpha = 0.95,
            label.padding = unit(0.16, "lines")
          )
      }

      if (isTRUE(input$show_points)) {
        p <- p + geom_point(
          aes(color = era),
          position = position_jitterdodge(jitter.width = 0, jitter.height = 0.14, dodge.width = 0.76),
          alpha = 0.3,
          size = 1.25,
          show.legend = FALSE
        ) +
          scale_color_manual(values = c(current = "#9a6f00", prior = "#5279b5"))
      }

      p
    },
    bg = "#ffffff"
  )

  # ── Histogram ──────────────────────────────────────────
  output$hist_plot <- renderPlot(
    {
      df <- fdf()
      req(nrow(df) > 0)
      max_yr <- input$yr[2]
      df$era <- ifelse(df$year == max_yr, "current", "prior")
      bw <- input$bw
      era_c <- c(current = "#b88200", prior = "#5279b5")
      era_l <- c(
        current = paste0("Current class (", max_yr, ")"),
        prior = paste0("Prior classes (", input$yr[1], "-", max_yr - 1, ")")
      )

      # Reference lines
      refs <- data.frame(
        x = c(300, 600, 1000, 2000),
        lbl = c("300", "600", "1,000", "2,000 mi")
      )

      base_theme <- theme_minimal(base_family = "Manrope") +
        theme(
          plot.background = element_rect(fill = "#ffffff", color = NA),
          panel.background = element_rect(fill = "#ffffff", color = NA),
          panel.grid.major = element_line(color = "#ebeff6", linewidth = 0.5),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(color = "#d8deea", fill = NA, linewidth = 0.6),
          axis.text = element_text(color = "#3b4f73", size = 9),
          axis.title = element_text(color = "#22395f", size = 10, face = "bold"),
          axis.title.x = element_text(margin = margin(t = 10)),
          axis.title.y = element_text(margin = margin(r = 10)),
          legend.background = element_rect(fill = "#ffffff", color = "#d8deea"),
          legend.text = element_text(color = "#445a82", size = 8.5),
          legend.title = element_text(color = "#22395f", size = 9, face = "bold"),
          legend.key = element_rect(fill = NA, color = NA),
          strip.background = element_rect(fill = "#eef4ff", color = "#d8deea"),
          strip.text = element_text(color = "#1a447f", size = 8.5, face = "bold"),
          plot.margin = margin(12, 16, 12, 12)
        )

      if (input$hist_mode == "overlay") {
        p <- ggplot(df, aes(x = distance_miles)) +
          geom_histogram(
            data = filter(df, era == "prior"),
            aes(fill = era), binwidth = bw, alpha = 0.18,
            color = "#44689f", linewidth = 0.6, position = "identity"
          ) +
          geom_histogram(
            data = filter(df, era == "current"),
            aes(fill = era), binwidth = bw, alpha = 0.90,
            color = "#866100", linewidth = 0.4, position = "identity"
          )

        if (input$dens) {
          nc <- nrow(filter(df, era == "current"))
          np <- nrow(filter(df, era == "prior"))
          if (nc > 3) {
            p <- p + stat_density(
              data = filter(df, era == "current"),
              aes(y = after_stat(density) * nc * bw, x = distance_miles),
              geom = "line", color = "#a57500", linewidth = 1.2, inherit.aes = FALSE
            )
          }
          if (np > 3) {
            p <- p + stat_density(
              data = filter(df, era == "prior"),
              aes(y = after_stat(density) * np * bw, x = distance_miles),
              geom = "line", color = "#44689f", linewidth = 1.05,
              linetype = "dashed", inherit.aes = FALSE
            )
          }
        }

        if (isTRUE(input$show_refs)) {
          p <- p +
            geom_vline(xintercept = refs$x, color = "#98a7c2", linewidth = 0.7, linetype = "dashed")
        }

        p <- p +
          annotate("text",
            x = refs$x + 22, y = Inf, label = refs$lbl,
            vjust = 1.3, hjust = 0, color = "#627898", size = 2.7,
            family = "Manrope"
          ) +
          scale_fill_manual(values = era_c, labels = era_l, name = "Class") +
          scale_x_continuous(
            labels = label_comma(suffix = " mi"),
            breaks = c(0, 300, 600, 1000, 1500, 2000, 2500, 3000),
            limits = c(0, NA),
            expand = expansion(mult = c(0.01, 0.03))
          ) +
          scale_y_continuous(expand = expansion(mult = c(0, 0.10))) +
          labs(
            x = "Distance from Hometown to Campus (miles)",
            y = "Number of Recruits"
          ) +
          base_theme +
          theme(legend.position = "top", legend.direction = "horizontal")
      } else {
        p <- ggplot(df, aes(x = distance_miles)) +
          geom_histogram(
            data = filter(df, era == "prior"),
            aes(fill = era),
            binwidth = bw, position = "identity",
            alpha = 0.16,
            color = "#44689f", linewidth = 0.52
          ) +
          geom_histogram(
            data = filter(df, era == "current"),
            aes(fill = era),
            binwidth = bw, position = "identity",
            alpha = 0.88,
            color = "#866100", linewidth = 0.36
          ) +
          scale_fill_manual(values = era_c, labels = era_l, name = "Class") +
          scale_x_continuous(
            labels = label_comma(suffix = " mi"),
            breaks = c(0, 500, 1000, 2000, 3000),
            expand = expansion(mult = c(0.01, 0.03))
          ) +
          scale_y_continuous(expand = expansion(mult = c(0, 0.14))) +
          facet_wrap(~team, ncol = 4, scales = "free_y") +
          labs(x = "Distance from Hometown to Campus (miles)", y = "Recruits") +
          base_theme +
          theme(
            legend.position = "top",
            strip.text = element_text(size = 8),
            axis.text = element_text(size = 7.5)
          )

        if (isTRUE(input$show_refs)) {
          p <- p + geom_vline(
            xintercept = c(300, 1000, 2000), color = "#98a7c2",
            linewidth = 0.5, linetype = "dotted"
          )
        }
      }
      p
    },
    bg = "#ffffff"
  )
}

shinyApp(ui, server)
