# ============================================================
#  Big 12 Basketball Recruiting Radar
#  Data loaded from recruits_data.csv (generated by scrape_recruits.R)
#
#  To refresh data:
#    source('scrape_recruits.R')
# ============================================================

library(shiny)
library(ggplot2)
library(dplyr)
library(scales)
library(stringr)

# ── on3.com team slugs ────────────────────────────────────
team_slugs <- c(
  "Arizona"        = "arizona-wildcats",
  "Arizona State"  = "arizona-state-sun-devils",
  "Baylor"         = "baylor-bears",
  "BYU"            = "byu-cougars",
  "Cincinnati"     = "cincinnati-bearcats",
  "Colorado"       = "colorado-buffaloes",
  "Houston"        = "houston-cougars",
  "Iowa State"     = "iowa-state-cyclones",
  "Kansas"         = "kansas-jayhawks",
  "Kansas State"   = "kansas-state-wildcats",
  "Oklahoma State" = "oklahoma-state-cowboys",
  "TCU"            = "tcu-horned-frogs",
  "Texas Tech"     = "texas-tech-red-raiders",
  "UCF"            = "ucf-knights",
  "Utah"           = "utah-utes",
  "West Virginia"  = "west-virginia-mountaineers"
)
big12_teams <- names(team_slugs)

# ── Campus coordinates (lat, lon) ─────────────────────────
campus_coords <- list(
  "Arizona"        = c(32.2319, -110.9501),
  "Arizona State"  = c(33.4242, -111.9281),
  "Baylor"         = c(31.5489, -97.1131),
  "BYU"            = c(40.2518, -111.6493),
  "Cincinnati"     = c(39.1329, -84.5150),
  "Colorado"       = c(40.0076, -105.2659),
  "Houston"        = c(29.7174, -95.3412),
  "Iowa State"     = c(42.0267, -93.6465),
  "Kansas"         = c(38.9543, -95.2558),
  "Kansas State"   = c(39.1836, -96.5717),
  "Oklahoma State" = c(36.1269, -97.0682),
  "TCU"            = c(32.7096, -97.3640),
  "Texas Tech"     = c(33.5843, -101.8783),
  "UCF"            = c(28.6024, -81.2001),
  "Utah"           = c(40.7649, -111.8421),
  "West Virginia"  = c(39.6350, -79.9542)
)

# ── Team brand colors ─────────────────────────────────────
team_colors <- c(
  "Arizona"        = "#AB0520", "Arizona State"  = "#8C1D40",
  "Baylor"         = "#154734", "BYU"            = "#002E5D",
  "Cincinnati"     = "#E00122", "Colorado"       = "#CFB87C",
  "Houston"        = "#C8102E", "Iowa State"     = "#F1BE48",
  "Kansas"         = "#0051A5", "Kansas State"   = "#512888",
  "Oklahoma State" = "#FF7300", "TCU"            = "#4D1979",
  "Texas Tech"     = "#CC0000", "UCF"            = "#FFC904",
  "Utah"           = "#BE0000", "West Virginia"  = "#002855"
)

# ── Haversine distance (miles) ────────────────────────────
haversine <- function(lat1, lon1, lat2, lon2) {
  R <- 3958.8
  phi1 <- lat1 * pi / 180
  phi2 <- lat2 * pi / 180
  dphi <- (lat2 - lat1) * pi / 180
  dlam <- (lon2 - lon1) * pi / 180
  a <- sin(dphi / 2)^2 + cos(phi1) * cos(phi2) * sin(dlam / 2)^2
  2 * R * asin(pmin(1, sqrt(a)))
}

# ── City → (lat,lon) lookup table ────────────────────────
# Covers every city that commonly appears in on3 recruiting data
city_db <- list(
  # Texas
  "Houston, TX" = c(29.760, -95.370), "Dallas, TX" = c(32.776, -96.797),
  "San Antonio, TX" = c(29.425, -98.494), "Austin, TX" = c(30.266, -97.750),
  "Fort Worth, TX" = c(32.725, -97.321), "El Paso, TX" = c(31.761, -106.487),
  "Lubbock, TX" = c(33.577, -101.856), "Amarillo, TX" = c(35.222, -101.831),
  "Waco, TX" = c(31.549, -97.146), "Tyler, TX" = c(32.351, -95.302),
  "Beaumont, TX" = c(30.086, -94.102), "Corpus Christi, TX" = c(27.800, -97.397),
  "Midland, TX" = c(31.997, -102.078), "Odessa, TX" = c(31.845, -102.368),
  "Plano, TX" = c(33.020, -96.699), "Arlington, TX" = c(32.736, -97.108),
  "Laredo, TX" = c(27.506, -99.507), "Pasadena, TX" = c(29.691, -95.209),
  "Mesquite, TX" = c(32.764, -96.599), "McAllen, TX" = c(26.204, -98.230),
  "Killeen, TX" = c(31.117, -97.728), "Pearland, TX" = c(29.563, -95.286),
  "Frisco, TX" = c(33.150, -96.823), "Richardson, TX" = c(32.948, -96.729),
  "Garland, TX" = c(32.913, -96.638), "Irving, TX" = c(32.814, -96.949),
  "Stephenville, TX" = c(32.220, -98.202),
  # Southeast
  "Atlanta, GA" = c(33.749, -84.388), "Charlotte, NC" = c(35.227, -80.843),
  "Raleigh, NC" = c(35.779, -78.638), "Durham, NC" = c(35.994, -78.899),
  "Greensboro, NC" = c(36.073, -79.792), "Winston-Salem, NC" = c(36.100, -80.244),
  "Memphis, TN" = c(35.149, -90.052), "Nashville, TN" = c(36.166, -86.784),
  "Knoxville, TN" = c(35.961, -83.921), "Chattanooga, TN" = c(35.045, -85.309),
  "Jacksonville, FL" = c(30.332, -81.656), "Orlando, FL" = c(28.538, -81.379),
  "Miami, FL" = c(25.761, -80.192), "Tampa, FL" = c(27.948, -82.458),
  "Tallahassee, FL" = c(30.438, -84.281), "Gainesville, FL" = c(29.651, -82.325),
  "Fort Lauderdale, FL" = c(26.122, -80.143), "West Palm Beach, FL" = c(26.715, -80.064),
  "Hialeah, FL" = c(25.858, -80.278), "St. Petersburg, FL" = c(27.773, -82.640),
  "Miami Gardens, FL" = c(25.942, -80.246), "Palm Bay, FL" = c(28.035, -80.589),
  "Birmingham, AL" = c(33.521, -86.803), "Huntsville, AL" = c(34.730, -86.586),
  "Mobile, AL" = c(30.696, -88.043), "Montgomery, AL" = c(32.361, -86.279),
  "Jackson, MS" = c(32.299, -90.184), "Gulfport, MS" = c(30.367, -89.095),
  "New Orleans, LA" = c(29.951, -90.071), "Baton Rouge, LA" = c(30.443, -91.187),
  "Shreveport, LA" = c(32.526, -93.749), "Lafayette, LA" = c(30.224, -92.020),
  "Savannah, GA" = c(32.080, -81.099), "Macon, GA" = c(32.841, -83.633),
  "Columbia, SC" = c(34.000, -81.035), "Greenville, SC" = c(34.852, -82.399),
  "Charleston, SC" = c(32.776, -79.931),
  # Midwest
  "Chicago, IL" = c(41.878, -87.630), "Rockford, IL" = c(42.271, -89.094),
  "Peoria, IL" = c(40.694, -89.589), "Joliet, IL" = c(41.526, -88.082),
  "Champaign, IL" = c(40.117, -88.244), "Springfield, IL" = c(39.801, -89.644),
  "Indianapolis, IN" = c(39.768, -86.158), "Fort Wayne, IN" = c(41.130, -85.129),
  "Evansville, IN" = c(37.975, -87.556), "Kokomo, IN" = c(40.487, -86.134),
  "Columbus, OH" = c(39.961, -82.999), "Cleveland, OH" = c(41.499, -81.695),
  "Cincinnati, OH" = c(39.103, -84.512), "Toledo, OH" = c(41.663, -83.555),
  "Akron, OH" = c(41.081, -81.519), "Canton, OH" = c(40.798, -81.379),
  "Dayton, OH" = c(39.759, -84.192),
  "Detroit, MI" = c(42.332, -83.046), "Grand Rapids, MI" = c(42.966, -85.656),
  "Flint, MI" = c(43.013, -83.688), "Lansing, MI" = c(42.733, -84.556),
  "Warren, MI" = c(42.492, -83.027), "Ann Arbor, MI" = c(42.281, -83.748),
  "Milwaukee, WI" = c(43.039, -87.907), "Madison, WI" = c(43.073, -89.401),
  "Green Bay, WI" = c(44.519, -88.020), "Oshkosh, WI" = c(44.025, -88.543),
  "Minneapolis, MN" = c(44.978, -93.265), "St. Paul, MN" = c(44.955, -93.102),
  "Rochester, MN" = c(44.023, -92.470), "Duluth, MN" = c(46.786, -92.101),
  "Kansas City, MO" = c(39.099, -94.578), "St. Louis, MO" = c(38.627, -90.199),
  "Springfield, MO" = c(37.215, -93.298), "Branson, MO" = c(36.644, -93.218),
  "Omaha, NE" = c(41.257, -96.004), "Lincoln, NE" = c(40.813, -96.703),
  "Sioux Falls, SD" = c(43.549, -96.700), "Fargo, ND" = c(46.877, -96.789),
  "Des Moines, IA" = c(41.600, -93.609), "Cedar Rapids, IA" = c(42.008, -91.645),
  "Wichita, KS" = c(37.692, -97.337), "Overland Park, KS" = c(38.982, -94.671),
  "Oklahoma City, OK" = c(35.467, -97.517), "Tulsa, OK" = c(36.154, -95.993),
  "Norman, OK" = c(35.221, -97.440), "Broken Arrow, OK" = c(36.061, -95.791),
  "Little Rock, AR" = c(34.746, -92.290), "Fayetteville, AR" = c(36.062, -94.158),
  # Northeast
  "New York, NY" = c(40.713, -74.006), "Brooklyn, NY" = c(40.650, -73.950),
  "Bronx, NY" = c(40.845, -73.865), "Queens, NY" = c(40.728, -73.795),
  "Yonkers, NY" = c(40.931, -73.899), "Syracuse, NY" = c(43.048, -76.147),
  "Buffalo, NY" = c(42.887, -78.879), "Rochester, NY" = c(43.158, -77.616),
  "Albany, NY" = c(42.651, -73.755), "Farmingdale, NY" = c(40.732, -73.443),
  "Glen Head, NY" = c(40.845, -73.628),
  "Philadelphia, PA" = c(39.952, -75.165), "Pittsburgh, PA" = c(40.440, -79.996),
  "Allentown, PA" = c(40.602, -75.470), "Lancaster, PA" = c(40.038, -76.306),
  "Harrisburg, PA" = c(40.274, -76.884),
  "Newark, NJ" = c(40.735, -74.172), "Jersey City, NJ" = c(40.729, -74.077),
  "Boston, MA" = c(42.360, -71.058), "Worcester, MA" = c(42.263, -71.802),
  "Springfield, MA" = c(42.101, -72.590), "Lynn, MA" = c(42.467, -70.944),
  "Hartford, CT" = c(41.764, -72.685), "Bridgeport, CT" = c(41.179, -73.190),
  "Waterbury, CT" = c(41.558, -73.052),
  "Providence, RI" = c(41.824, -71.413),
  "Washington, DC" = c(38.907, -77.037), "Baltimore, MD" = c(39.290, -76.612),
  "Richmond, VA" = c(37.541, -77.436), "Virginia Beach, VA" = c(36.853, -75.978),
  "Norfolk, VA" = c(36.851, -76.291), "Chesapeake, VA" = c(36.769, -76.287),
  "Hampton, VA" = c(37.031, -76.345),
  # Mountain/West
  "Denver, CO" = c(39.739, -104.984), "Colorado Springs, CO" = c(38.834, -104.822),
  "Aurora, CO" = c(39.729, -104.832), "Lakewood, CO" = c(39.705, -105.082),
  "Pueblo, CO" = c(38.255, -104.609),
  "Phoenix, AZ" = c(33.448, -112.074), "Tucson, AZ" = c(32.221, -110.969),
  "Mesa, AZ" = c(33.415, -111.831), "Chandler, AZ" = c(33.307, -111.841),
  "Tempe, AZ" = c(33.425, -111.940), "Scottsdale, AZ" = c(33.494, -111.926),
  "Las Vegas, NV" = c(36.175, -115.137), "Henderson, NV" = c(36.040, -114.982),
  "North Las Vegas, NV" = c(36.199, -115.117), "Reno, NV" = c(39.529, -119.814),
  "Salt Lake City, UT" = c(40.760, -111.891), "Provo, UT" = c(40.233, -111.658),
  "Ogden, UT" = c(41.223, -111.974), "St. George, UT" = c(37.104, -113.584),
  "Albuquerque, NM" = c(35.085, -106.651), "Santa Fe, NM" = c(35.687, -105.938),
  "Boise, ID" = c(43.615, -116.202), "Meridian, ID" = c(43.612, -116.392),
  "Spokane, WA" = c(47.659, -117.426), "Seattle, WA" = c(47.607, -122.332),
  "Tacoma, WA" = c(47.253, -122.445), "Bellevue, WA" = c(47.611, -122.192),
  "Portland, OR" = c(45.523, -122.676), "Eugene, OR" = c(44.051, -123.087),
  # California
  "Los Angeles, CA" = c(34.052, -118.244), "San Diego, CA" = c(32.715, -117.157),
  "San Jose, CA" = c(37.339, -121.894), "San Francisco, CA" = c(37.775, -122.419),
  "Fresno, CA" = c(36.737, -119.787), "Sacramento, CA" = c(38.582, -121.494),
  "Long Beach, CA" = c(33.770, -118.194), "Oakland, CA" = c(37.804, -122.271),
  "Bakersfield, CA" = c(35.373, -119.019), "Anaheim, CA" = c(33.836, -117.915),
  "Santa Ana, CA" = c(33.746, -117.868), "Riverside, CA" = c(33.954, -117.395),
  "Stockton, CA" = c(37.958, -121.291), "Modesto, CA" = c(37.640, -120.997),
  "Oxnard, CA" = c(34.197, -119.177), "Moreno Valley, CA" = c(33.937, -117.230),
  "Pomona, CA" = c(34.055, -117.752), "Torrance, CA" = c(33.836, -118.341),
  "Pasadena, CA" = c(34.148, -118.144), "Compton, CA" = c(33.896, -118.220),
  "Santa Maria, CA" = c(34.952, -120.436), "Napa, CA" = c(38.297, -122.286),
  "Castaic, CA" = c(34.489, -118.628), "Inglewood, CA" = c(33.962, -118.353),
  # Other US
  "Anchorage, AK" = c(61.218, -149.900), "Honolulu, HI" = c(21.307, -157.858),
  "Louisville, KY" = c(38.252, -85.758), "Lexington, KY" = c(38.040, -84.459),
  "Fayetteville, NC" = c(35.053, -78.879), "Asheville, NC" = c(35.579, -82.554),
  "Gary, IN" = c(41.593, -87.347), "South Bend, IN" = c(41.676, -86.252),
  "Athens, GA" = c(33.960, -83.378), "Augusta, GA" = c(33.471, -81.975),
  "Murfreesboro, TN" = c(35.846, -86.390), "Clarksville, TN" = c(36.530, -87.359),
  "Lake City, MN" = c(44.449, -92.268),
  # International / cities without state
  "Kinshasa" = c(-4.322, 15.322), "Kinshasa, Congo" = c(-4.322, 15.322),
  "Yaoundé" = c(3.867, 11.517), "Cameroon" = c(3.848, 11.502),
  "Rome, Rome" = c(41.902, 12.496), "Rome, Italy" = c(41.902, 12.496),
  "Montreal, QC" = c(45.501, -73.568), "Edmonton, AB" = c(53.546, -113.490),
  "Vancouver, BC" = c(49.246, -123.117), "Toronto, ON" = c(43.653, -79.383),
  "Germany" = c(51.166, 10.452), "Berlin, Germany" = c(52.520, 13.405),
  "France" = c(46.227, 2.213), "Paris, France" = c(48.857, 2.352),
  "Nigeria" = c(9.082, 8.675), "Lagos, Nigeria" = c(6.455, 3.384),
  "Senegal" = c(14.497, -14.452), "Australia" = c(-25.274, 133.775),
  "Spain" = c(40.463, -3.749), "Serbia" = c(44.017, 21.006),
  "Croatia" = c(45.100, 15.202), "Bahamas" = c(25.025, -77.980),
  "Jamaica" = c(18.110, -77.297),
  "Hickory, NC" = c(35.729, -81.338)
)

# ── Geocode a hometown string ─────────────────────────────
geocode_city <- function(hometown) {
  if (is.na(hometown) || nchar(trimws(hometown)) == 0) {
    return(NULL)
  }
  key <- trimws(hometown)
  # Direct
  if (!is.null(city_db[[key]])) {
    return(city_db[[key]])
  }
  # Remove parentheses
  key2 <- str_replace_all(key, "[()]", "") %>% trimws()
  if (!is.null(city_db[[key2]])) {
    return(city_db[[key2]])
  }
  # Try just first two comma parts
  parts <- str_split(key2, ",")[[1]]
  if (length(parts) >= 2) {
    k3 <- paste0(trimws(parts[1]), ", ", trimws(parts[2]))
    if (!is.null(city_db[[k3]])) {
      return(city_db[[k3]])
    }
  }
  NULL
}

# ── Scrape one page from on3.com ──────────────────────────
scrape_on3_page <- function(team, year, slug, verbose = TRUE) {
  url <- sprintf(
    "https://www.on3.com/college/%s/basketball/%d/commits/",
    slug, year
  )
  if (verbose) message(sprintf("  Fetching %s %d ...", team, year))

  tryCatch(
    {
      resp <- GET(
        url,
        user_agent("Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"),
        add_headers(
          "Accept-Language" = "en-US,en;q=0.9",
          "Accept" = "text/html,application/xhtml+xml"
        ),
        timeout(20)
      )
      if (status_code(resp) != 200) {
        return(NULL)
      }

      html_text <- content(resp, as = "text", encoding = "UTF-8")

      # Extract Hometown values — on3 uses "Hometown:\n(City, ST)" pattern
      # Multiple extraction strategies
      hometowns <- character(0)

      # Strategy 1: regex on raw HTML for hometown patterns
      m1 <- str_match_all(
        html_text,
        "Hometown[^(]*\\(([^)]{2,40})\\)"
      )[[1]]
      if (nrow(m1) > 0) hometowns <- c(hometowns, m1[, 2])

      # Strategy 2: parse with rvest
      if (length(hometowns) == 0) {
        page <- read_html(html_text)
        # Look for dt/dd pairs
        dts <- page %>%
          html_nodes("dt") %>%
          html_text(trim = TRUE)
        dds <- page %>%
          html_nodes("dd") %>%
          html_text(trim = TRUE)
        ht_idx <- which(str_detect(dts, "(?i)hometown"))
        if (length(ht_idx) > 0 && max(ht_idx) <= length(dds)) {
          hometowns <- dds[ht_idx]
          hometowns <- str_replace_all(hometowns, "[()]", "") %>% trimws()
        }
      }

      # Strategy 3: look for city-state pattern after "Hometown"
      if (length(hometowns) == 0) {
        m3 <- str_match_all(
          html_text,
          '"hometown"[^"]*"([A-Za-z ]+(?:,\\s*[A-Z]{2})?)"'
        )[[1]]
        if (nrow(m3) > 0) hometowns <- m3[, 2]
      }

      hometowns <- hometowns[nchar(trimws(hometowns)) > 1]
      hometowns <- trimws(hometowns)

      if (length(hometowns) == 0) {
        return(NULL)
      }

      data.frame(
        team = team, year = year, hometown = hometowns,
        stringsAsFactors = FALSE
      )
    },
    error = function(e) {
      message(sprintf("    Error: %s", e$message))
      NULL
    }
  )
}

# ── Compute distances ─────────────────────────────────────
add_distances <- function(df) {
  campus <- campus_coords
  df %>%
    rowwise() %>%
    mutate(
      coords = list(geocode_city(hometown)),
      ht_lat = if (!is.null(coords)) coords[1] else NA_real_,
      ht_lon = if (!is.null(coords)) coords[2] else NA_real_,
      camp_lat = campus[[team]][1],
      camp_lon = campus[[team]][2],
      distance_miles = if (!is.na(ht_lat)) {
        haversine(ht_lat, ht_lon, camp_lat, camp_lon)
      } else {
        NA_real_
      }
    ) %>%
    ungroup() %>%
    filter(!is.na(distance_miles)) %>%
    select(team, year, hometown, distance_miles)
}

# ── Load data from CSV ────────────────────────────────────
load_recruiting_data <- function(csv_file = "recruits_data.csv") {
  if (!file.exists(csv_file)) {
    warning(sprintf("Data file '%s' not found.\n  Run scrape_recruits.R to create it.", csv_file))
    return(data.frame(
      team = character(), year = integer(),
      hometown = character(), distance_miles = numeric()
    ))
  }
  message(sprintf("Loading data from %s...", csv_file))
  df <- read.csv(csv_file, stringsAsFactors = FALSE)
  message(sprintf("Loaded %d recruits", nrow(df)))
  df
}

# ─────────────────────────────────────────────────────────
#  UI
# ─────────────────────────────────────────────────────────
ui <- fluidPage(
  tags$head(
    tags$link(
      rel = "stylesheet",
      href = "https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@300;400;500;600&display=swap"
    ),
    tags$style(HTML("
      * { box-sizing:border-box; }
      body { background:#0e0f14; color:#e8e4dc;
             font-family:'DM Sans',sans-serif; margin:0; padding:0; }

      /* Header */
      .app-header {
        background:linear-gradient(135deg,#0e0f14 0%,#1a1c25 50%,#0e0f14 100%);
        border-bottom:2px solid #c8a84b;
        padding:20px 32px 14px;
        display:flex; align-items:flex-end; gap:14px;
      }
      .app-title { font-family:'Bebas Neue',sans-serif; font-size:2.6rem;
        letter-spacing:3px; color:#c8a84b; line-height:1; margin:0; }
      .app-sub { font-size:0.76rem; color:#7a7d8a; letter-spacing:1.5px;
        text-transform:uppercase; margin-bottom:3px; }
      .badge-conf { background:#c8a84b; color:#0e0f14;
        font-family:'Bebas Neue',sans-serif; font-size:0.82rem;
        letter-spacing:2px; padding:2px 10px; border-radius:3px;
        display:inline-block; margin-bottom:4px; }
      .badge-live { background:#1a2a1a; border:1px solid #2d5a2d;
        color:#5fd4a0; font-size:0.68rem; letter-spacing:1px;
        padding:2px 9px; border-radius:3px; display:inline-block;
        margin-bottom:4px; margin-left:6px; }

      /* Stats strip */
      .stats-strip { display:flex; gap:5px; padding:10px 22px;
        background:#13141a; border-bottom:1px solid #232530; flex-wrap:wrap; }
      .stat-card { background:#1a1c25; border:1px solid #2d3040;
        border-radius:5px; padding:7px 12px; flex:1; min-width:80px;
        text-align:center; transition:border-color 0.2s; }
      .stat-card:hover { border-color:#c8a84b; }
      .stat-val { font-family:'Bebas Neue',sans-serif; font-size:1.5rem;
        color:#c8a84b; line-height:1; }
      .stat-lbl { font-size:0.60rem; color:#7a7d8a; letter-spacing:1.5px;
        text-transform:uppercase; margin-top:2px; }

      /* Layout */
      .main-wrap { display:flex; min-height:calc(100vh - 96px); }

      /* Sidebar */
      .sidebar { width:252px; min-width:252px; background:#13141a;
        border-right:1px solid #232530; padding:18px 16px;
        display:flex; flex-direction:column; gap:16px; }
      .sec-lbl { font-size:0.64rem; letter-spacing:2.5px;
        text-transform:uppercase; color:#c8a84b; margin-bottom:6px;
        font-weight:600; }
      hr.sdiv { border:none; border-top:1px solid #232530; margin:2px 0; }
      .shiny-input-container { margin-bottom:0 !important; }
      label { color:#9da0ad !important; font-size:0.75rem !important;
              font-weight:500 !important; margin-bottom:3px !important; }
      .selectize-control .selectize-input {
        background:#1e2029 !important; border:1px solid #2d3040 !important;
        color:#e8e4dc !important; border-radius:4px !important;
        box-shadow:none !important; font-size:0.78rem !important; }
      .selectize-control .selectize-input.focus {
        border-color:#c8a84b !important;
        box-shadow:0 0 0 2px rgba(200,168,75,.15) !important; }
      .selectize-dropdown { background:#1e2029 !important;
        border:1px solid #2d3040 !important; color:#e8e4dc !important;
        font-size:0.78rem !important; }
      .selectize-dropdown-content .option:hover,
      .selectize-dropdown-content .option.active {
        background:#2d3040 !important; color:#c8a84b !important; }
      input[type=checkbox],input[type=radio] { accent-color:#c8a84b; }
      .checkbox label,.radio label { color:#e8e4dc !important;
        font-size:0.78rem !important; }
      .irs--shiny .irs-bar { background:#c8a84b !important; }
      .irs--shiny .irs-handle { background:#c8a84b !important;
        border-color:#c8a84b !important; }
      .irs--shiny .irs-from,.irs--shiny .irs-to,.irs--shiny .irs-single {
        background:#c8a84b !important; color:#0e0f14 !important;
        font-weight:600 !important; }
      .irs--shiny .irs-line { background:#2d3040 !important; }
      .irs--shiny .irs-grid-text { color:#7a7d8a !important;
        font-size:0.66rem !important; }
      .shiny-options-group { display:flex; flex-direction:column; gap:3px; }

      /* Plot area */
      .plot-area { flex:1; padding:18px 22px; background:#0e0f14; overflow:auto; }
      .plot-hdr { display:flex; justify-content:space-between;
        align-items:baseline; margin-bottom:10px; }
      .plot-ttl { font-family:'Bebas Neue',sans-serif; font-size:1.35rem;
        letter-spacing:2px; color:#e8e4dc; }
      .plot-cap { font-size:0.68rem; color:#555868; }
      .loading-box { color:#c8a84b; font-family:'Bebas Neue',sans-serif;
        font-size:1.1rem; letter-spacing:2px; padding:60px 20px;
        text-align:center; }
      .loading-sub { font-family:'DM Sans',sans-serif; font-size:0.8rem;
        color:#7a7d8a; margin-top:10px; line-height:1.6; }
    "))
  ),

  # ── Header ──────────────────────────────────────────────
  div(
    class = "app-header",
    div(
      div(class = "badge-conf", "BIG 12 CONFERENCE"),
      span(class = "badge-live", "● LIVE DATA · on3.com"),
      div(class = "app-title", "RECRUITING RADAR")
    ),
    div(
      style = "margin-left:auto; text-align:right;",
      div(class = "app-sub", "High school recruit distance · miles from hometown to campus")
    )
  ),

  # ── Stats strip ─────────────────────────────────────────
  div(
    class = "stats-strip",
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_n", inline = TRUE)),
      div(class = "stat-lbl", "Recruits")
    ),
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_med", inline = TRUE)),
      div(class = "stat-lbl", "Median Miles")
    ),
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_avg", inline = TRUE)),
      div(class = "stat-lbl", "Avg Miles")
    ),
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_loc", inline = TRUE)),
      div(class = "stat-lbl", "≤300 mi %")
    ),
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_natl", inline = TRUE)),
      div(class = "stat-lbl", ">1,000 mi %")
    ),
    div(
      class = "stat-card", div(class = "stat-val", textOutput("s_intl", inline = TRUE)),
      div(class = "stat-lbl", ">2,500 mi %")
    )
  ),

  # ── Body ────────────────────────────────────────────────
  div(
    class = "main-wrap",

    # Sidebar
    div(
      class = "sidebar",
      div(
        div(class = "sec-lbl", "Year Range"),
        sliderInput("yr", NULL,
          min = 2021, max = 2025,
          value = c(2021, 2025), step = 1, sep = "", ticks = TRUE
        )
      ),
      hr(class = "sdiv"),
      div(
        div(class = "sec-lbl", "Teams"),
        selectizeInput("teams", NULL,
          choices = big12_teams,
          selected = big12_teams, multiple = TRUE,
          options = list(
            placeholder = "Select teams…",
            plugins = list("remove_button")
          )
        )
      ),
      hr(class = "sdiv"),
      div(
        div(class = "sec-lbl", "Display Mode"),
        radioButtons("mode", NULL,
          choices = c(
            "All Teams Overlaid" = "overlay",
            "Facet by Team" = "facet"
          ),
          selected = "overlay"
        )
      ),
      hr(class = "sdiv"),
      div(
        div(class = "sec-lbl", "Bin Width (miles)"),
        sliderInput("bw", NULL, min = 50, max = 400, value = 150, step = 25)
      ),
      hr(class = "sdiv"),
      div(
        div(class = "sec-lbl", "Options"),
        checkboxInput("dens", "Overlay density curve", TRUE),
        checkboxInput("local_hl", "Highlight local zone (≤300 mi)", FALSE),
        checkboxInput("drop_intl", "Exclude international recruits (>4000 mi)", FALSE)
      ),
      hr(class = "sdiv"),
      div(
        div(class = "sec-lbl", "Legend"),
        div(
          style = "font-size:0.68rem;color:#9da0ad;line-height:1.8;",
          HTML("🟨 <b style='color:#c8a84b;'>Gold solid</b> = current year<br>
                🔲 <b style='color:#5a6080;'>Faded blue</b> = prior years<br>
                Dashed lines = distance markers")
        )
      ),
      hr(class = "sdiv"),
      div(
        div(class = "sec-lbl", "Data"),
        div(
          style = "font-size:0.67rem;color:#555868;line-height:1.5;",
          "Data loaded from recruits_data.csv.", br(),
          "Run scrape_recruits.R to refresh."
        ),
        actionButton("rescrape", "🔄 Reload Data",
          style = "margin-top:8px;width:100%;background:#1a1c25;
                 color:#c8a84b;border:1px solid #c8a84b;border-radius:4px;
                 font-size:0.72rem;padding:5px 0;cursor:pointer;"
        )
      )
    ),

    # Plot area
    div(
      class = "plot-area",
      div(
        class = "plot-hdr",
        div(class = "plot-ttl", "Distance Traveled to Campus"),
        div(class = "plot-cap", textOutput("caption", inline = TRUE))
      ),
      uiOutput("content")
    )
  )
)

# ─────────────────────────────────────────────────────────
#  SERVER
# ─────────────────────────────────────────────────────────
server <- function(input, output, session) {
  rv_data <- reactiveVal(NULL)
  rv_loading <- reactiveVal(TRUE)

  # Initial load
  observe({
    rv_loading(TRUE)
    withProgress(
      message = "Loading recruit data…",
      detail = "Reading from recruits_data.csv",
      value = 0,
      {
        df <- tryCatch(load_recruiting_data("recruits_data.csv"),
          error = function(e) {
            showNotification(paste("Load error:", e$message), type = "error")
            data.frame(
              team = character(), year = integer(),
              hometown = character(), distance_miles = numeric()
            )
          }
        )
        rv_data(df)
      }
    )
    rv_loading(FALSE)
  })

  # Reload data button
  observeEvent(input$rescrape, {
    rv_loading(TRUE)
    withProgress(message = "Reloading data…", value = 0, {
      df <- tryCatch(load_recruiting_data("recruits_data.csv"),
        error = function(e) rv_data()
      )
      rv_data(df)
    })
    rv_loading(FALSE)
    showNotification("Data reloaded!", type = "message")
  })

  # ── Filtered reactive ──────────────────────────────────
  fdf <- reactive({
    req(rv_data(), nrow(rv_data()) > 0)
    df <- rv_data() %>%
      filter(
        team %in% input$teams,
        year >= input$yr[1],
        year <= input$yr[2]
      )
    if (input$drop_intl) df <- filter(df, distance_miles <= 4000)
    df
  })

  # ── Stats ──────────────────────────────────────────────
  output$s_n <- renderText({
    req(fdf())
    comma(nrow(fdf()))
  })
  output$s_med <- renderText({
    req(fdf())
    comma(round(median(fdf()$distance_miles)))
  })
  output$s_avg <- renderText({
    req(fdf())
    comma(round(mean(fdf()$distance_miles)))
  })
  output$s_loc <- renderText({
    req(fdf())
    paste0(round(mean(fdf()$distance_miles <= 300) * 100), "%")
  })
  output$s_natl <- renderText({
    req(fdf())
    paste0(round(mean(fdf()$distance_miles > 1000) * 100), "%")
  })
  output$s_intl <- renderText({
    req(fdf())
    paste0(round(mean(fdf()$distance_miles > 2500) * 100), "%")
  })
  output$caption <- renderText({
    req(fdf())
    paste0(
      length(input$teams), " teams · ",
      input$yr[1], "–", input$yr[2], " · ",
      nrow(fdf()), " recruits"
    )
  })

  # ── Content switch ─────────────────────────────────────
  output$content <- renderUI({
    if (rv_loading()) {
      div(
        class = "loading-box",
        div("⏳ LOADING DATA…"),
        div(
          class = "loading-sub",
          "Reading from recruits_data.csv", br(), br(),
          "To update with new recruiting data:", br(),
          "Run ",
          tags$code(
            style = "background:#1e2029;padding:2px 6px;border-radius:3px;",
            "source('scrape_recruits.R')"
          ),
          " in the R console"
        )
      )
    } else if (is.null(rv_data()) || nrow(rv_data()) == 0) {
      div(
        class = "loading-box",
        div("⚠️ NO DATA LOADED"),
        div(
          class = "loading-sub",
          "recruits_data.csv not found.", br(),
          "Run ",
          tags$code(
            style = "background:#1e2029;padding:2px 6px;border-radius:3px;",
            "source('scrape_recruits.R')"
          ),
          " to fetch and save data."
        )
      )
    } else {
      plotOutput("hist_plot", height = "570px", width = "100%")
    }
  })

  # ── Histogram ──────────────────────────────────────────
  output$hist_plot <- renderPlot(
    {
      df <- fdf()
      req(nrow(df) > 0)
      max_yr <- input$yr[2]
      df$era <- ifelse(df$year == max_yr, "current", "prior")
      bw <- input$bw

      # Reference lines
      refs <- data.frame(
        x = c(300, 600, 1000, 2000),
        lbl = c("300", "600", "1,000", "2,000 mi")
      )

      base_theme <- theme_minimal(base_family = "DM Sans") +
        theme(
          plot.background = element_rect(fill = "#0e0f14", color = NA),
          panel.background = element_rect(fill = "#13141a", color = NA),
          panel.grid.major = element_line(color = "#1e2029", linewidth = 0.5),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(color = "#2d3040", fill = NA, linewidth = 0.5),
          axis.text = element_text(color = "#7a7d8a", size = 9),
          axis.title = element_text(color = "#9da0ad", size = 10, face = "bold"),
          axis.title.x = element_text(margin = margin(t = 10)),
          axis.title.y = element_text(margin = margin(r = 10)),
          legend.background = element_rect(fill = "#13141a", color = "#2d3040"),
          legend.text = element_text(color = "#9da0ad", size = 8.5),
          legend.title = element_text(color = "#c8a84b", size = 9, face = "bold"),
          legend.key = element_rect(fill = NA, color = NA),
          strip.background = element_rect(fill = "#1a1c25", color = "#2d3040"),
          strip.text = element_text(color = "#c8a84b", size = 8.5, face = "bold"),
          plot.margin = margin(12, 16, 12, 12)
        )

      if (input$mode == "overlay") {
        era_c <- c(current = "#c8a84b", prior = "#3a4565")
        era_l <- c(
          current = paste0("Current class (", max_yr, ")"),
          prior = paste0("Prior classes (", input$yr[1], "–", max_yr - 1, ")")
        )

        p <- ggplot(df, aes(x = distance_miles)) +
          geom_vline(
            xintercept = refs$x, color = "#2d3040",
            linewidth = 0.7, linetype = "dashed"
          ) +
          geom_histogram(
            data = filter(df, era == "prior"),
            aes(fill = era), binwidth = bw, alpha = 0.42,
            color = "#1a1c25", linewidth = 0.25, position = "identity"
          ) +
          geom_histogram(
            data = filter(df, era == "current"),
            aes(fill = era), binwidth = bw, alpha = 0.86,
            color = "#0e0f14", linewidth = 0.35, position = "identity"
          )

        if (input$dens) {
          nc <- nrow(filter(df, era == "current"))
          np <- nrow(filter(df, era == "prior"))
          if (nc > 3) {
            p <- p + stat_density(
              data = filter(df, era == "current"),
              aes(y = after_stat(density) * nc * bw, x = distance_miles),
              geom = "line", color = "#c8a84b", linewidth = 1.2, inherit.aes = FALSE
            )
          }
          if (np > 3) {
            p <- p + stat_density(
              data = filter(df, era == "prior"),
              aes(y = after_stat(density) * np * bw, x = distance_miles),
              geom = "line", color = "#607090", linewidth = 0.9,
              linetype = "dashed", inherit.aes = FALSE
            )
          }
        }

        if (input$local_hl) {
          p <- p +
            annotate("rect",
              xmin = 0, xmax = 300, ymin = -Inf, ymax = Inf,
              fill = "#5fd4a0", alpha = 0.07
            ) +
            annotate("text",
              x = 150, y = Inf, label = "LOCAL\nZONE",
              vjust = 1.4, color = "#5fd4a0", size = 3,
              fontface = "bold", family = "DM Sans"
            )
        }

        p <- p +
          annotate("text",
            x = refs$x + 22, y = Inf, label = refs$lbl,
            vjust = 1.3, hjust = 0, color = "#555868", size = 2.7,
            family = "DM Sans"
          ) +
          scale_fill_manual(values = era_c, labels = era_l, name = "Class") +
          scale_x_continuous(
            labels = label_comma(suffix = " mi"),
            breaks = c(0, 300, 600, 1000, 1500, 2000, 2500, 3000),
            limits = c(0, NA),
            expand = expansion(mult = c(0.01, 0.03))
          ) +
          scale_y_continuous(expand = expansion(mult = c(0, 0.10))) +
          labs(
            x = "Distance from Hometown to Campus (miles)",
            y = "Number of Recruits"
          ) +
          base_theme +
          theme(legend.position = "top", legend.direction = "horizontal")
      } else {
        # Facet
        pal <- team_colors[names(team_colors) %in% input$teams]
        p <- ggplot(df, aes(x = distance_miles, fill = team, alpha = era)) +
          geom_histogram(
            binwidth = bw, position = "identity",
            color = "#1a1c25", linewidth = 0.2
          ) +
          scale_alpha_manual(
            values = c(current = 0.88, prior = 0.32),
            labels = c(
              current = paste0("Current (", max_yr, ")"),
              prior = "Prior"
            ), name = "Era"
          ) +
          scale_fill_manual(values = pal, guide = "none") +
          scale_x_continuous(
            labels = label_comma(suffix = " mi"),
            breaks = c(0, 500, 1000, 2000, 3000),
            expand = expansion(mult = c(0.01, 0.03))
          ) +
          scale_y_continuous(expand = expansion(mult = c(0, 0.14))) +
          facet_wrap(~team, ncol = 4, scales = "free_y") +
          labs(x = "Distance from Hometown to Campus (miles)", y = "Recruits") +
          base_theme +
          theme(
            legend.position = "top",
            strip.text = element_text(size = 8),
            axis.text = element_text(size = 7.5)
          )

        if (input$local_hl) {
          p <- p + geom_vline(
            xintercept = 300, color = "#5fd4a0",
            linewidth = 0.5, linetype = "dotted"
          )
        }
      }
      p
    },
    bg = "#0e0f14"
  )
}

shinyApp(ui, server)
